name: help
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.17.1 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: 2.0.5-beta
  auto_size_text: 3.0.0
  flutter_svg: ^1.0.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/help/assets/images/ellipse1.png
    - packages/help/assets/images/ellipse2.png
    - packages/help/assets/images/bonbonparenthelpingchilddomathhomework12.png
    - packages/help/assets/images/vector.svg
    - packages/help/assets/images/bonbongeolocationiconandrouteline2.png
    - packages/help/assets/images/bonbongeolocationiconandrouteline1.png
    - packages/help/assets/images/bonbonparenthelpingchilddomathhomework11.png
    - packages/help/assets/images/vector2.svg
    - packages/help/assets/images/vector3.svg
    - packages/help/assets/images/vector4.svg
    - ""
    - packages/help/assets/images/pale441.png
    - packages/help/assets/images/cliplibrary21.png
    - packages/help/assets/images/clipcustomerservice1.png
    - packages/help/assets/images/urban9601.png
    - packages/help/assets/images/bonbonwomandoctorlistenstotheheartbeat11.png
    - packages/help/assets/images/religioussymbolspngdownloadimage1.png
    - packages/help/assets/images/cliproadtoschool1.png
    - packages/help/assets/images/5862596522074544093208764569268126843142144n1.png
    - packages/help/assets/images/b343cfacc4364db8974cc37fb4971a1c1.png
    - packages/help/assets/images/caposona21.png
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - >
    - >
      packages/help/assets/images/bonbonfriendlydoctorhelpingyounggirltreatingpsychologicalproblem32.png
